' 會員模組類別圖
@startuml Auth_Module
left to right direction

package "Controllers" {
    class Auth_Controller
}

package "Services" {
    class Auth_Service {
        +register_user_service()
        +authenticate_user_service()
        +reset_password_service()
        +change_password_service()
        +get_customer_profile_service()
        +update_customer_profile_service()
    }
}

package "Repositories" {
    class Auth_Repository {
        +add_user()
        +add_customer()
        +add_restaurant()
        +get_last_store()
        +get_customer()
        +is_authorized()
        +get_restaurant()
        +update_user_password()
        +get_user()
        +get_customer_by_email()
        +get_restaurant_by_email()
        +get_customer_info()
        +update_customer_info()
        
    }
}

package "Database" {
    class UserTable {
        +username: String
        +password: String
        +role: Integer
    }
}

Auth_Controller --> Auth_Service
Auth_Service --> Auth_Repository
Auth_Repository --> UserTable

@enduml