' 系統類別圖
@startuml sys_class_diagram
left to right direction

package "Controllers" {
    class Auth_Controller
    class Cart_Controller
    class Menu_Controller
    class Order_Controller
    class Restaurant_Controller
}

package "Services" {
    class Auth_Service {
        +register_user_service()
        +authenticate_user_service()
        +reset_password_service()
        +change_password_service()
        +get_customer_profile_service()
        +update_customer_profile_service()
    }
    class Cart_Service {
        +add_item_to_cart_service()
        +get_cart_items_service()
        +remove_item_from_cart_service()
    }
    class Menu_Service {
        +get_open_stores_service()
        +get_all_restaurants_service()
        +get_menu_items_by_restaurant_id_service()
        +get_restaurant_by_id_service()
    }
    class Order_Service {
        +get_all_orders_service()
        +checkout_order_service()
        +add_note_service()
        +return_order_service()
    }
    class Restaurant_Service {
        +get_store_info_service()
        +update_store_info_service()
        +add_menu_item_service()
        +get_menu_item_by_id_service()
        +update_menu_item_service()
        +delete_menu_item_service()
        +get_pending_orders_service()
        +get_history_orders_service()
        +update_order_status_service()
        +update_payment_status_service()
    }
}

package "Repositories" {
    class Auth_Repository {
        +add_user()
        +add_customer()
        +add_restaurant()
        +get_last_store()
        +get_customer()
        +is_authorized()
        +get_restaurant()
        +update_user_password()
        +get_user()
        +get_customer_by_email()
        +get_restaurant_by_email()
        +get_customer_info()
        +update_customer_info()
        
    }
    class Cart_Repository {
        +add_one_item_in_cart()
        +check_order()
        +get_restaurant_id_for_item()
        +check_existing_orders()
        +delete_order_from_cart()
        +fetch_cart_item()
        +remove_from_cart()
        +update_order_status_if_empty()
    }
    class Menu_Repository {
        +get_all_restaurants()
        +get_menu_items_by_restaurant_id()
        +get_restaurant_by_id()
    }
    class Order_Repository {
        +fetch_all_orders()
        +checkout_order()
        +add_note_to_order()
        +return_order()
        +check_existing_orders()
        +delete_order_from_cart()
    }
    class Restaurant_Repository {
        +get_restaurant_info()
        +update_restaurant_info()
        +item_exists()
        +get_last_item()
        +add_item()
        +get_item_info()
        +get_menu_item_by_id()
        +update_item_info()
        +delete_item()
        +get_pending_orders()
        +get_history_orders()
        +update_order_status()
        +update_payment_status()
    }
}

package "Database" {
    class UserTable {
        +username: String
        +password: String
        +role: Integer
    }
    class Customer {
        +customer_id: Integer
        +name: String
        +phone: String
        +email: String
        +username: String
    }
    class Restaurant {
        +restaurant_id: Integer
        +restaurant_name: String
        +phone: String
        +address: String
        +business_hours: String
        +manager: String
        +manager_email: String
        +icon: String
        +username: String
    }
    class MenuItem {
        +item_id: Integer
        +restaurant_id: Integer
        +item_name: String
        +price: Integer
        +description: String
        +status: Integer
        +item_image: String
    }
    class OrderTable {
        +order_id: Integer
        +customer_id: Integer
        +order_status: Integer
        +order_time: DateTime
        +total_amount: Integer
        +order_pick_up_time: DateTime
        +payment_method: Integer
        +payment_status: Integer
        +order_note: String
    }
    class OrderDetail {
        +order_id: Integer
        +order_detail_id: Integer
        +item_id: Integer
        +item_price: Integer
        +quantity: Integer
        +item_note: String
    }
}

Auth_Controller --> Auth_Service
Cart_Controller --> Cart_Service
Menu_Controller --> Menu_Service
Order_Controller --> Order_Service
Restaurant_Controller --> Restaurant_Service

Auth_Service --> Auth_Repository
Cart_Service --> Cart_Repository
Menu_Service --> Menu_Repository
Order_Service --> Order_Repository
Restaurant_Service --> Restaurant_Repository

Auth_Repository --> UserTable
Cart_Repository --> OrderTable
Menu_Repository --> MenuItem
Order_Repository --> OrderTable
Restaurant_Repository --> Restaurant

Customer --> UserTable
Restaurant --> UserTable
MenuItem --> Restaurant
OrderTable --> Customer
OrderDetail --> OrderTable
OrderDetail --> MenuItem

@enduml